
const jobListings = [
  {
    id: 1,
    title: "Content Writer",
    company: "Techie Blog",
    location: "Dhaka",
    type: "Part-time",
    salary: "5000 BDT/month",
    description: "Looking for a creative content writer to write tech-related articles.",
    skillsRequired: ["Writing", "SEO", "Research"],
  },
  {
    id: 2,
    title: "Graphic Designer",
    company: "Design Hub",
    location: "Chittagong",
    type: "Remote",
    salary: "3000 BDT/project",
    description: "Design posters and banners for social media platforms.",
    skillsRequired: ["Photoshop", "Illustrator"],
  },
  {
    id: 3,
    title: "Data Entry Operator",
    company: "Fast Solutions",
    location: "Dhaka",
    type: "Part-time",
    salary: "4000 BDT/month",
    description: "Perform data entry tasks and maintain databases.",
    skillsRequired: ["Typing", "Excel"],
  },
  {
    id: 4,
    title: "Social Media Manager",
    company: "Buzz Media",
    location: "Sylhet",
    type: "Part-time",
    salary: "6000 BDT/month",
    description: "Manage and grow the company’s social media presence.",
    skillsRequired: ["Social Media", "Content Creation"],
  },
  {
    id: 5,
    title: "Tutor - Mathematics",
    company: "Private Client",
    location: "Dhaka",
    type: "Part-time",
    salary: "4000 BDT/month",
    description: "Provide math tutoring to high school students.",
    skillsRequired: ["Mathematics", "Teaching"],
  },
  {
    id: 6,
    title: "Web Developer",
    company: "StartUp Ltd.",
    location: "Remote",
    type: "Contract",
    salary: "8000 BDT/project",
    description: "Develop a responsive company website.",
    skillsRequired: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: 7,
    title: "Customer Service Agent",
    company: "Easy Help",
    location: "Dhaka",
    type: "Part-time",
    salary: "5000 BDT/month",
    description: "Assist customers with inquiries via phone and email.",
    skillsRequired: ["Communication", "Problem Solving"],
  },
  {
    id: 8,
    title: "Video Editor",
    company: "Creative Studio",
    location: "Remote",
    type: "Freelance",
    salary: "4000 BDT/project",
    description: "Edit promotional videos for social media campaigns.",
    skillsRequired: ["Video Editing", "Premiere Pro"],
  },
  {
    id: 9,
    title: "Event Coordinator",
    company: "Eventify",
    location: "Rajshahi",
    type: "Part-time",
    salary: "6000 BDT/month",
    description: "Help coordinate and manage small-scale events.",
    skillsRequired: ["Event Planning", "Coordination"],
  },
  {
    id: 10,
    title: "App Tester",
    company: "Mobile Dev",
    location: "Remote",
    type: "Part-time",
    salary: "3000 BDT/project",
    description: "Test mobile applications for bugs and provide feedback.",
    skillsRequired: ["App Testing", "Bug Reporting"],
  },
  {
    id: 11,
    title: "SEO Specialist",
    company: "Digital Marketing Co.",
    location: "Khulna",
    type: "Part-time",
    salary: "7000 BDT/month",
    description: "Improve the company’s website ranking through SEO strategies.",
    skillsRequired: ["SEO", "Google Analytics"],
  },
  {
    id: 12,
    title: "Delivery Rider",
    company: "Quick Parcel",
    location: "Barishal",
    type: "Part-time",
    salary: "4000 BDT/month",
    description: "Deliver packages within the city area.",
    skillsRequired: ["Motorcycle License", "Time Management"],
  },
  {
    id: 13,
    title: "Translator (English-Bangla)",
    company: "Global Docs",
    location: "Remote",
    type: "Freelance",
    salary: "5000 BDT/project",
    description: "Translate documents from English to Bangla.",
    skillsRequired: ["Translation", "English", "Bangla"],
  },
  {
    id: 14,
    title: "Sales Associate",
    company: "Retail Pro",
    location: "Dhaka",
    type: "Part-time",
    salary: "4500 BDT/month",
    description: "Assist customers in-store and manage inventory.",
    skillsRequired: ["Sales", "Customer Service"],
  },
  {
    id: 15,
    title: "Photography Assistant",
    company: "Lens Art",
    location: "Chittagong",
    type: "Part-time",
    salary: "3000 BDT/event",
    description: "Assist the photographer during events.",
    skillsRequired: ["Photography", "Creativity"],
  },
  {
    id: 16,
    title: "UI/UX Designer",
    company: "Innovative Designs",
    location: "Remote",
    type: "Freelance",
    salary: "6000 BDT/project",
    description: "Design user-friendly interfaces for websites and apps.",
    skillsRequired: ["UI/UX", "Figma", "Adobe XD"],
  },
  {
    id: 17,
    title: "Fitness Trainer",
    company: "Fit Life",
    location: "Sylhet",
    type: "Part-time",
    salary: "5000 BDT/month",
    description: "Train clients in fitness routines and provide health guidance.",
    skillsRequired: ["Fitness", "Training"],
  },
  {
    id: 18,
    title: "Content Moderator",
    company: "SocialBuzz",
    location: "Remote",
    type: "Part-time",
    salary: "4000 BDT/month",
    description: "Moderate content on social media platforms.",
    skillsRequired: ["Moderation", "Attention to Detail"],
  },
  {
    id: 19,
    title: "Research Assistant",
    company: "Edu Research",
    location: "Dhaka",
    type: "Part-time",
    salary: "6000 BDT/month",
    description: "Assist with academic research and data collection.",
    skillsRequired: ["Research", "Data Analysis"],
  },
  {
    id: 20,
    title: "Virtual Assistant",
    company: "Online Services",
    location: "Remote",
    type: "Part-time",
    salary: "3500 BDT/month",
    description: "Manage emails, schedules, and administrative tasks for clients.",
    skillsRequired: ["Communication", "Time Management"],
  }
];
